fix: Make enum creation idempotent in pet icons migration
The migration was failing because it tried to create enum types
that already existed (PetType, Gender, etc.).

Changed from:
  CREATE TYPE "PetType" AS ENUM (...)

To:
  DO $$ BEGIN
    CREATE TYPE "PetType" AS ENUM (...);
  EXCEPTION
    WHEN duplicate_object THEN null;
  END $$;

This makes the migration safe to run multiple times and fixes:
ERROR: type "PetType" already exists