fix: Add missing lodash dependency to frontend
The frontend tests were failing because lodash is required by
@craco/craco but was not installed as a dependency.

Error:
  Cannot find module 'lodash'
  Require stack:
  - .../frontend/node_modules/@craco/craco/dist/lib/utils.js

Added lodash to frontend dependencies.

Note: @types/lodash already exists in devDependencies.